services:
  - type: web
    name: alking-pro-trading
    runtime: docker
    repo: https://github.com/cvn3443-ctrl/Alking-Pro-Trading-Server
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
